Repository NavisGames/Valorant-Tracking-by-NavisGames, pull requests merged in 2022-12, with the labels that each got.

#30 Switchable Gamemodes for Match History
  ValorantTracking/ValorantTracking.py
  ValorantTracking/functions.py
Labels: enhancement

#32 Redesigning gamemode filters
  .github/release-drafter.yml
  ValorantTracking/ValorantTracking.py
Labels: rework

#35 Average damage per round and Average Combat score
  .github/PULL_REQUEST_TEMPLATE.md
  ValorantTracking/Valorant Tracking.py
  ValorantTracking/functions.py
Labels: enhancement

#38 Reworking match_History
  ValorantTracking/Valorant Tracking.py
  ValorantTracking/functions.py
Labels: rework

#41 creating config.yml file
  .github/ISSUE_TEMPLATE/config.yml
Labels: other

#42 Improve English grammar
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  SECURITY.md
Labels: other

#43 Rework of stats and accuracy
  ValorantTracking/ValorantTracking.py
Labels: rework, other

#45 Small changes for almost everything
  .gitignore
  ValorantTracking/ValorantTracking.py
  ValorantTracking/functions.py
  ValorantTracking/requirements.txt
  requirements.txt
Labels: other

#46 Rework MMR History & added Peak rank
  ValorantTracking/ValorantTracking.py
  ValorantTracking/functions.py
Labels: enhancement, rework
