Repository NavisGames/Valorant-Tracking-by-NavisGames, pull requests merged in 2022-11, with the labels that each got.

#14 Fixed leaderboard layout
  Version 2.0/ValorantTracking.py
Labels: bugfix

#17 Creating a Website for the Tracker
  Website/README.md
  Website/index.html
  Website/logo.svg
Labels: enhancement

#18 Adding darkmode
  Version 2.0/ValorantTracking.py
Labels: rework

#21 Delete old Version
  old_version/Ranks/ASCENDANT 1.png
  old_version/Ranks/ASCENDANT 2.png
  old_version/Ranks/ASCENDANT 3.png
  old_version/Ranks/BRONZE 1.png
  old_version/Ranks/BRONZE 2.png
  old_version/Ranks/BRONZE 3.png
  old_version/Ranks/DIAMOND 1.png
  old_version/Ranks/DIAMOND 2.png
  old_version/Ranks/DIAMOND 3.png
  old_version/Ranks/GOLD 1.png
  old_version/Ranks/GOLD 2.png
  old_version/Ranks/GOLD 3.png
  old_version/Ranks/IMMORTAL 1.png
  old_version/Ranks/IMMORTAL 2.png
  old_version/Ranks/IMMORTAL 3.png
  old_version/Ranks/IRON 1.png
  old_version/Ranks/IRON 2.png
  old_version/Ranks/IRON 3.png
  old_version/Ranks/PLATINUM 1.png
  old_version/Ranks/PLATINUM 2.png
  old_version/Ranks/PLATINUM 3.png
  old_version/Ranks/RADIANT.png
  old_version/Ranks/SILVER 1.png
  old_version/Ranks/SILVER 2.png
  old_version/Ranks/SILVER 3.png
  old_version/Ranks/UNRANKED.png
  old_version/ValorantTracking.py
  old_version/icon.ico
  old_version/icon.png
Labels: documentation

#22 Creating an own website!
  Images/Screenshots/Bundle.png
  Images/Screenshots/Leaderboard.png
  Images/Screenshots/Main.png
  index.html
  script.js
  style.css
Labels: enhancement

#24 Add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#25 Initial commit
  SECURITY.md
Labels: documentation

#28 See headshot rate in individual matches
  ValorantTracking/ValorantTracking.py
Labels: enhancement
